#!/bin/bash
set -eux

export VER="1.4.5"
if [ ! -d ~/.local/bin ];
then
    echo "Please create ~/.local/bin and add it to your path!"
    exit 1
fi
cd /tmp
wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
unzip packer_${VER}_linux_amd64.zip
mv packer ~/.local/bin
rm packer_${VER}_linux_amd64.zip
cd -

source $1/bin/activate $1 && pip install jmespath pycryptodome pyyaml docker boto3 ansible
