import os

# DB settings
DB_HOST = 'THE_API_ADDRESS_GOES_HERE'
DB_SECRET = 'THESECRETPASSPHRASEGOESHERE'

# RabbitMQ settings
RABBIT_USERNAME = os.environ['RABBIT_USERNAME']
RABBIT_PASSWORD = os.environ['RABBIT_PASSWORD']
RABBIT_ENDPOINT = os.environ['RABBIT_ENDPOINT']

SCRIPTBOT_INSTANCES = int(os.environ['NUM_SCRIPTBOTS'])
