#!/bin/sh
### BEGIN INIT INFO
# Provides:          poipoi
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iCTF poipoi service
# Description:       iCTF poipoi service
### END INIT INFO

# Author: UCSB iCTF 2013 Team <ctf-admin@lists.cs.ucsb.edu>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="poipoi iCTF service"
NAME=poipoi             # Introduce the short server's name here

START_SCRIPT=/ictf/services/poipoi/start.sh
STOP_SCRIPT=/ictf/services/poipoi/stop.sh

# Exit if the package is not installed
[ -x $START_SCRIPT ] || exit 0
[ -x $STOP_SCRIPT ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
        su -l --command $START_SCRIPT poipoi
}

#
# Function that stops the daemon/service
#
do_stop()
{
        su -l --command $STOP_SCRIPT poipoi
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
    do_start
  ;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	do_start
	;;
  *)
	exit 3
	;;
esac

:

