FROM ictf_2_melt

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nginx uwsgi uwsgi-plugin-python mysql-server python-pip python-virtualenv python-mysqldb python-dev awscli

RUN pip install --upgrade pip setuptools pyOpenSSL ndg-httpsclient pyasn1
